# ##################配置端口####################
server:
  port: 4001
#####################配置注册中心###############
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5001/eureka
####################配置服务名字#####################
spring:
  application:
    name: Zuul

  #################redis配置###################
  redis:
    database: 9
    host: 192.168.100.231
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: -1
        max-wait: -1
        max-idle: 25
        min-idle: 10
    timeout: 5000
################ Zuul动态服务配置服务路由 #########################
zuul:
  routes:
    #   aaaaa: 可以随便写
    aaaa:
      path: /myUser/**
      # 服务名
      serviceId: ServerProjectUser
      # 设置Cookie可传递
      #sensitiveHeaders:
    ####简洁写法
    #serviceeureka: /myservice/**
  #禁止外部访问(排除某些路由) 接口 是set集合
  #ignored-patterns:
    #- /myservice/getAll
    #- /serviceeureka/getAll
    #- /**/getAll

    #忽略全部服务敏感头都可传递Cookie
  sensitive-headers: