# ##################配置端口####################
server:
  port: 5016
#####################配置注册中心###############
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5025/eureka
####################配置服务名字#####################
spring:
  application:
    name: Gateway
##################路由转发###########################
zuul:
  routes:
    token:
      path: /token/**
      serviceId: serverOAuth
    one:
      path: /myOne/**
      serviceId: ServerProjectOne
##########敏感头配置空 不拦截##########
  sensitive-headers:

