###############  JWT 安全配置  ################################
security:
  oauth2:
    client:
      client-id: servr6025
      client-secret: 123456
    resource:
      jwt:
        key-uri: http://localhost:5056/oauth/token_key